export const STYLES = {
    container: {
        minHeight: '100vh',
        backgroundColor: '#0A0B0D',
        color: '#FFFFFF',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        padding: '20px',
    },
    card: {
        backgroundColor: '#16181D',
        borderRadius: '32px',
        padding: '48px',
        width: '100%',
        maxWidth: '440px',
        border: '1px solid rgba(255, 255, 255, 0.05)',
        boxShadow: '0 24px 48px rgba(0, 0, 0, 0.5)',
        textAlign: 'center' as const,
    },
    title: {
        fontSize: '32px',
        fontWeight: '800',
        marginBottom: '12px',
        letterSpacing: '-0.03em',
        background: 'linear-gradient(to bottom, #FFFFFF 0%, #A0AEC0 100%)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
    },
    subtitle: {
        fontSize: '17px',
        color: '#FFFFFF',
        marginBottom: '42px',
        lineHeight: '1.6',
    },
    button: {
        width: '100%',
        padding: '18px',
        borderRadius: '18px',
        fontSize: '18px',
        fontWeight: '700',
        border: 'none',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        display: 'flex',
        justifyContent: 'center' as const,
        alignItems: 'center' as const,
        gap: '12px',
    },
    primaryButton: {
        background: 'linear-gradient(135deg, #ffda34 0%, #ffd000 100%)',
        color: '#000000',
        boxShadow: '0 8px 16px rgba(255, 218, 52, 0.25)',
    },
    secondaryButton: {
        background: 'rgba(255, 255, 255, 0.04)',
        color: '#FFFFFF',
        border: '1px solid rgba(255, 255, 255, 0.08)',
        marginTop: '16px',
    },
    addressContainer: {
        background: 'rgba(255, 218, 52, 0.08)',
        border: '1px solid rgba(255, 218, 52, 0.15)',
        padding: '12px 20px',
        borderRadius: '14px',
        marginBottom: '32px',
    },
    addressText: {
        color: '#ffda34',
        fontSize: '14px',
        fontWeight: '600',
        fontFamily: 'monospace',
    },
    inputGroup: {
        marginBottom: '16px',
        textAlign: 'left' as const,
    },
    label: {
        color: '#FFFFFF',
        fontSize: '14px',
        fontWeight: '600',
        marginBottom: '8px',
        display: 'block',
    },
    input: {
        width: '100%',
        padding: '14px 16px',
        borderRadius: '12px',
        border: '1px solid rgba(255, 255, 255, 0.08)',
        background: 'rgba(255, 255, 255, 0.03)',
        color: '#FFFFFF',
        fontSize: '15px',
        fontFamily: 'inherit',
        outline: 'none',
        transition: 'all 0.2s ease',
        boxSizing: 'border-box' as const,
    }
} as const;
